[program:urban-haven-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/urban-haven/artisan queue:work database --sleep=3 --tries=3 --backoff=30 --max-time=3600
directory=/var/www/urban-haven
user=www-data
numprocs=2
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/var/www/urban-haven/storage/logs/queue.log
